name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: Build Gateway Service
        working-directory: ./gateway-service
        run: go build -o gateway-service ./cmd/...
      - name: Build User Service
        working-directory: ./user-service
        run: go build -o user-service ./cmd/...