name: CI Pipeline
on:
  push:
    branches: [ "*" ]
  pull_request:
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.0

      - name: Run lint (gateway-service)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.4.0
          working-directory: ./gateway-service

      - name: Run lint (user-service)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v2.4.0
          working-directory: ./user-service

      - name: Run tests (gateway-service)
        working-directory: ./gateway-service
        run: go test ./...

      - name: Run tests (user-service)
        working-directory: ./user-service
        run: go test ./...